name: SSH Tunnel & Forwarding fork
version: 1.2.1
slug: autossh
description: >-
  Permanent HA forwarding and domain linking through an SSH tunnel
url: 'https://github.com/ThomDietrich/home-assistant-addons'
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
init: false
host_network: true
map:
  - 'config:rw'

options:
  hostname: ''
  ssh_port: 22
  username: ubuntu
  remote_forwarding:
    - '4433:192.168.9.32:443'
  other_ssh_options: '-v -N'
  force_keygen: false
schema:
  hostname: str
  ssh_port: int
  username: str
  remote_forwarding:
    - str
  other_ssh_options: str
  force_keygen: bool
